import type { NextPage } from "next";
import { signIn, signOut, useSession } from "next-auth/react";
import Head from "next/head";
import TaskInput from "../components/TaskInput";
import TaskItem from "../components/TaskItem";
import { trpc } from "../utils/trpc";

const Home: NextPage = () => {
    const tasks = trpc.proxy.task.getTask.useQuery();

    const secretMsg = trpc.proxy.auth.getSecretMessage.useQuery();

    return (
        <>
            <Head>
                <title>Create T3 App</title>
                <meta name="description" content="Generated by create-t3-app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main className="flex flex-col items-center  min-h-screen p-4 mx-auto bg-neutral-800 w-full">
                <div className="border border-orange-500 w-1/2 px-5 py-8 rounded-xl flex flex-col items-center">
                    <h1 className="text-4xl font-semibold text-white pb-8">
                        Task list
                    </h1>
                    <div className="w-full flex flex-col items-center space-y-4">
                        <TaskInput />
                        {tasks.data ? (
                            <>
                                {tasks.data.map((item, index) => (
                                    <TaskItem
                                        key={item.id}
                                        id={item.id}
                                        content={item.taskContent}
                                        isDone={item.isDone}
                                    />
                                ))}
                            </>
                        ) : (
                            <>
                                <span>loading...</span>
                            </>
                        )}
                    </div>
                </div>
                <div className="flex space-x-4 mt-3 text-white">
                    <button
                        className="border border-orange-600 px-5 py-1 rounded-2xl"
                        onClick={() => signIn()}
                    >
                        <span>Sign In</span>
                    </button>
                    <button
                        className="border border-orange-600 px-5 py-1 rounded-2xl"
                        onClick={() => signOut()}
                    >
                        <span>Sign Out</span>
                    </button>
                </div>
                <div>
                    <span>{secretMsg.data}</span>
                </div>
            </main>
        </>
    );
};

export default Home;
